# Generated by Django 6.0.4 on 2026-06-23 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Numero_contacto', models.CharField(max_length=15)),
                ('Encargo', models.CharField(choices=[('Retiro', 'Retiro'), ('Envio', 'Envio')], max_length=20)),
                ('Sector', models.CharField(choices=[('Compañias', 'Compañias'), ('La_Serena', 'La_Serena'), ('Coquimbo', 'Coquimbo')], max_length=20)),
                ('Datos_de_Localizacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invenatario_Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Categoria', models.CharField(blank=True, choices=[('Papeleria', 'Papeleria'), ('Alimento', 'Alimento'), ('Material_Escolar', 'Material_Escolar')], max_length=50, null=True)),
                ('Precio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('Stock', models.IntegerField()),
                ('Nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ESCOLAR', 'Articulos escolares'), ('BAZAR', 'Regalos/Bazar'), ('ALIMENTO', 'Colaciones/Alimentos')], default='ESCOLAR', max_length=20)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_coste', models.IntegerField(blank=True, default=0)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
