# Generated by Django 6.0.5 on 2026-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('ESCOLAR', 'Artículos Escolares'), ('REGALO', 'Regalos/Bazar'), ('ALIMENTO', 'Colaciones/Alimentos')], default='ESCOLAR', max_length=20)),
            ],
        ),
    ]
