# Generated by Django 6.0.5 on 2026-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_coste',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
