# Generated by Django 6.0.4 on 2026-06-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encargos',
        ),
    ]
