# Generated by Django 6.0.5 on 2026-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ESCOLAR', 'Artículos Escolares'), ('BAZAR', 'Regalos/Bazar'), ('ALIMENTO', 'Colaciones/Alimentos')], default='ESCOLAR', max_length=20),
        ),
    ]
