# Generated by Django 6.0.5 on 2026-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_coste',
            field=models.IntegerField(default=0),
        ),
    ]
