# Generated by Django 6.0.5 on 2026-06-02 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_coste',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ESCOLAR', 'Artículos Escolares'), ('BAZAR', 'Regalos/Bazar'), ('ALIMENTO', 'Colaciones/Alimentos')], default='ESCOLAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
