# Generated by Django 6.0.5 on 2026-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aym', '0004_producto_precio_coste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_coste',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
